cert_center/urls.py
from django.conf.urls import url
from . import views

app_name = 'cert_center'
urlpatterns = [
    url(r'^show/(?P<pk>\d+)$', views.show_by_id, name='show_by_id'),
    url(r'^show_req/(?P<pk>\d+)$', views.show_req_by_id, name='show_req_by_id'),
    url(r'^all$', views.show_all, name='all'),
]

digital_key/urls.py
from django.conf.urls import url
from . import views

app_name = 'digital_key'
urlpatterns = [
    url(r'^$', views.show_all, name='all'),
    url(r'^show/(?P<key_id>[0-9]+)$', views.show_by_id, name='show_by_id'),

    url(r'^edit/(?P<key_id>[0-9]+)$', views.edit_by_id, name='edit_by_id'),
    url(r'^remove/(?P<key_id>[0-9]+)$', views.remove_by_id, name='remove_by_id'),
    url(r'^add$', views.create, name='add'),

    url(r'^loc/detail/(?P<pk>\d+)$', views.location_detail, name='loc_detail'),
    url(r'^loc/all$', views.location_list, name='loc_all'),

    url(r'^system/all$', views.system_list, name='sys_all' ),
    url(r'^system/detail/(?P<pk>\d+)$', views.system_detail, name='sys_detail'),

    url(r'^assignment/all$', views.assignment_list, name='asgn_all'),
    url(r'^assignment/detail/(?P<pk>\d+)$', views.assignment_detail, name='asgn_detail'),
]

export/urls.py
from django.conf.urls import url
from . import views

app_name = 'export'
urlpatterns = [
    url(r'^xlsx$', views.export_key_xlsx, name='xlsx'),
]

keyHolder/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from .views import index

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^admin/', admin.site.urls, name='admin'),
    url(r'^keys/', include('digital_key.urls')),
    url(r'^employees/', include('employee.urls')),
    url(r'^centers/', include('cert_center.urls')),
    url(r'^manuals/', include('key_manual.urls')),
    url(r'^export/', include('export.urls')),
]

cert_center/models.py
from django.db import models


# Create your models here.
class CertificationCenter(models.Model):
    name = models.CharField(max_length=255)
    name_full = models.CharField(max_length=255, blank=True, default='')

    link = models.URLField(blank=True)
    description = models.TextField(blank=True)

    def __str__(self):
        return self.name


class CertRequirement(models.Model):
    name = models.CharField(max_length=255)
    name_full = models.CharField(max_length=255, blank=True, default='')

    link = models.URLField(blank=True)
    description = models.TextField(blank=True)
    actual_date = models.DateField(blank=True, null=True)
    center = models.ForeignKey(CertificationCenter)

    def __str__(self):
        return self.name

digitalkey/models.py
from django.db import models
import datetime
from django.utils import timezone
from employee.models import Employee, EmployeeGroup

import logging

# Create your models here.


logger = logging.getLogger(__name__)


class KeyType(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class KeyAssignment(models.Model):
    name = models.CharField(max_length=200)
    description = models.TextField(blank=True)

    def __str__(self):
        return self.name


class KeyLocation(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField(blank=True)

    def __str__(self):
        return self.name


class DigitalKey(models.Model):
    name = models.CharField(max_length=255)
    serial = models.CharField(max_length=200)
    description = models.TextField(blank=True)

    date_begin = models.DateField(blank=True, null=True)
    date_expire = models.DateField(blank=True, null=True)
    renewal_time = models.PositiveIntegerField(blank=True, default=0)

    type = models.ForeignKey(KeyType, blank=True, null=True)
    assignment = models.ForeignKey(KeyAssignment, blank=True, null=True)
    location = models.ForeignKey(KeyLocation, blank=True, null=True)

    cert_holder = models.ForeignKey(Employee, blank=True, null=True, related_name='cert_set')
    key_receiver = models.ForeignKey(Employee, blank=True, null=True, related_name='key_set')
    employee_group = models.ForeignKey(EmployeeGroup, blank=True, null=True)

    copy_of = models.ForeignKey('DigitalKey', blank=True, null=True,
                                on_delete=models.SET_NULL,
                                limit_choices_to={'copy_of': None})

    def get_copies(self):
        return DigitalKey.objects.filter(copy_of=self)

    def is_copy(self):
        return bool(self.copy_of)

    def __str__(self):
        return self.name


class CertificationCenter(models.Model):
    name = models.CharField(max_length=255)
    site = models.URLField(blank=True)
    description = models.TextField(blank=True)

    def __str__(self):
        return self.name


class CertRequirements(models.Model):
    name = models.CharField(max_length=255)
    site = models.URLField(blank=True)
    description = models.TextField(blank=True)
    actual_date = models.DateField(blank=True)
    center = models.ForeignKey(CertificationCenter)

    def __str__(self):
        return self.name

cert_center/views.py
from django.shortcuts import render, get_object_or_404

# Create your views here.
from cert_center.models import CertificationCenter, CertRequirement
from digital_key.models import DigitalKey
from digital_key.support import DigitalKeyWrapper


def show_by_id(request, pk):
    cert_center = get_object_or_404(CertificationCenter, pk=pk)
    requirements = cert_center.certrequirement_set.all()
    keys = cert_center.digitalkey_set.all()
    return render(request, 'cert_center/center_detail.html', {
        'cert_center': cert_center,
        'requirements': requirements,
        'keys': (DigitalKeyWrapper(key) for key in keys)
    })


def show_all(request):
    centers = CertificationCenter.objects.all()
    return render(request, 'cert_center/center_list.html', {
        'centers': centers
    })


def show_req_by_id(request, pk):
    requirement = get_object_or_404(CertRequirement, pk=pk)
    return render(request, 'cert_center/req_detail.html', {
        'requirement': requirement
    })

cert_center/templates/cert_center/center_detail.html
{% extends 'base.html' %}
{% block content %}
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <strong>{{ cert_center.name }}</strong>
                    {% if cert_center.link %}
                        <a href="{{ cert_center.link }}" target="_blank">(сайт)</a>
                    {% endif %}

                    {#                    <a href="{% url 'cert_center:show_by_id' cert_center.id %}">#}
                    {#                        <span class="glyphicon glyphicon-pencil pull-right"></span>#}
                    {#                    </a>#}
                </div>
                <div class="panel-body">
                    {{ cert_center.description|linebreaks }}
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6">
            <div class="panel panel-default">
                <div class="panel-heading">Требования:</div>
                <div class="panel-body">
                    <ul>
                        {% for requirement in requirements %}
                            <li>
                                <a href="{% url 'cert_center:show_req_by_id' requirement.id %}">{{ requirement.name }}</a>
                            </li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <div class="panel panel-default">
                <div class="panel-heading">Ключи:</div>
                <div class="panel-body">
                    <ul>
                        {% for view in keys %}
                            <li><a href="{% url 'digital_key:show_by_id' view.key.id %}">{{ view.key }}</a>
                                <span class="label label-{{ view.get_label_class }}">{{ view.key.date_expire|date:'d.m.y' }}</span>
                                {% if view.key.location %}
                                    <a href="{% url 'employee:show_group_by_id' view.key.location_id %}">
                                        <span class="label label-default">{{ view.key.location }}</span>
                                    </a>
                                {% endif %}
                            </li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

cert_center/templates/cert_center/center_list.html
{% extends 'base.html' %}
{% block content %}
    <div id="toolbar">
        <div class="form-inline" role="form">
        </div>
    </div>
    <table data-toggle="table"
           data-height="700"
           data-toolbar="#toolbar"
           data-search="true">
        <thead>
        <tr style="display: none">
            <th data-sortable="true">Название</th>
            <th data-sortable="true">Ключей</th>
        </tr>
        </thead>
        <tbody>
        {% for center in centers %}
            <tr style="display: none">
                <td><a href="{% url 'cert_center:show_by_id' center.id %}">{{ center.name }}</a></td>
                <td>{{ center.digitalkey_set.count }}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}

cert_center/templates/cert_center/req_detail.html
{% extends 'base.html' %}
{% block content %}
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    Основная информация:
                </div>
                <div class="panel-body">
                    <p><strong>{{ requirement.name }}</strong>
                        {% if requirement.actual_date %}
                            <small>от {{ requirement.actual_date }}</small>
                        {% endif %}
                        {% if requirement.link %}
                            <a href="{{ requirement.link }}" target="_blank">(ссылка)</a>
                        {% endif %}
                    </p>
                    <p><strong>Описание:</strong></p>
                    {{ requirement.description |linebreaks }}
                </div>
            </div>
        </div>
    </div>
{% endblock %}