digital_key/urls.py
from django.conf.urls import url
from . import views

app_name = 'digital_key'
urlpatterns = [
    url(r'^$', views.show_all, name='all'),
    url(r'^show/(?P<key_id>[0-9]+)$', views.show_by_id, name='show_by_id'),

    url(r'^edit/(?P<key_id>[0-9]+)$', views.edit_by_id, name='edit_by_id'),
    url(r'^remove/(?P<key_id>[0-9]+)$', views.remove_by_id, name='remove_by_id'),
    url(r'^add$', views.create, name='add'),

    url(r'^loc/detail/(?P<pk>\d+)$', views.location_detail, name='loc_detail'),
    url(r'^loc/all$', views.location_list, name='loc_all'),

    url(r'^system/all$', views.system_list, name='sys_all' ),
    url(r'^system/detail/(?P<pk>\d+)$', views.system_detail, name='sys_detail'),

    url(r'^assignment/all$', views.assignment_list, name='asgn_all'),
    url(r'^assignment/detail/(?P<pk>\d+)$', views.assignment_detail, name='asgn_detail'),
]

employee/urls.py
from django.conf.urls import url

from . import views

app_name = 'employee'
urlpatterns = [
    url(r'^$', views.EmployeeListView.as_view(), name='all'),
    url(r'^show/(?P<cid>[0-9]+)$', views.show_by_id, name='show_by_id'),
    url(r'^show_group/(?P<pk>\d+)$', views.show_group_by_id, name='group_detail'),
    url(r'^json/search$', views.show_all_by_name, name='json_by_name'),
    url(r'^edit/(?P<cid>[0-9]+)$', views.edit_by_id, name='edit_by_id'),
    url(r'^add$', views.create, name='add'),
    url(r'^remove/(?P<cid>[0-9]+)$', views.remove_by_id, name='remove'),

    url(r'^group/all$', views.EmployeeGroupsList.as_view(), name='group_all')

]

export/urls.py
from django.conf.urls import url
from . import views

app_name = 'export'
urlpatterns = [
    url(r'^xlsx$', views.export_key_xlsx, name='xlsx'),
]

keyHolder/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from .views import index

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^admin/', admin.site.urls, name='admin'),
    url(r'^keys/', include('digital_key.urls')),
    url(r'^employees/', include('employee.urls')),
    url(r'^centers/', include('cert_center.urls')),
    url(r'^manuals/', include('key_manual.urls')),
    url(r'^export/', include('export.urls')),
]

digitalkey/models.py
from django.db import models
import datetime
from django.utils import timezone
from employee.models import Employee, EmployeeGroup

import logging

# Create your models here.


logger = logging.getLogger(__name__)


class KeyType(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class KeyAssignment(models.Model):
    name = models.CharField(max_length=200)
    description = models.TextField(blank=True)

    def __str__(self):
        return self.name


class KeyLocation(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField(blank=True)

    def __str__(self):
        return self.name


class DigitalKey(models.Model):
    name = models.CharField(max_length=255)
    serial = models.CharField(max_length=200)
    description = models.TextField(blank=True)

    date_begin = models.DateField(blank=True, null=True)
    date_expire = models.DateField(blank=True, null=True)
    renewal_time = models.PositiveIntegerField(blank=True, default=0)

    type = models.ForeignKey(KeyType, blank=True, null=True)
    assignment = models.ForeignKey(KeyAssignment, blank=True, null=True)
    location = models.ForeignKey(KeyLocation, blank=True, null=True)

    cert_holder = models.ForeignKey(Employee, blank=True, null=True, related_name='cert_set')
    key_receiver = models.ForeignKey(Employee, blank=True, null=True, related_name='key_set')
    employee_group = models.ForeignKey(EmployeeGroup, blank=True, null=True)

    copy_of = models.ForeignKey('DigitalKey', blank=True, null=True,
                                on_delete=models.SET_NULL,
                                limit_choices_to={'copy_of': None})

    def get_copies(self):
        return DigitalKey.objects.filter(copy_of=self)

    def is_copy(self):
        return bool(self.copy_of)

    def __str__(self):
        return self.name


class CertificationCenter(models.Model):
    name = models.CharField(max_length=255)
    site = models.URLField(blank=True)
    description = models.TextField(blank=True)

    def __str__(self):
        return self.name


class CertRequirements(models.Model):
    name = models.CharField(max_length=255)
    site = models.URLField(blank=True)
    description = models.TextField(blank=True)
    actual_date = models.DateField(blank=True)
    center = models.ForeignKey(CertificationCenter)

    def __str__(self):
        return self.name

employee/models.py
from django.db import models


# Create your models here.


class Employee(models.Model):
    name = models.CharField(max_length=255)
    name_full = models.CharField(max_length=255, blank=True, default='')

    description = models.TextField(blank=True, default="")

    def get_contact_info(self):
        return self.contactinfo_set.all()

    def __str__(self):
        return self.name


class EmployeeGroup(models.Model):
    name = models.CharField(max_length=255)
    name_full = models.CharField(max_length=255, blank=True, default='')

    description = models.TextField(blank=True, default="")
    members = models.ManyToManyField(Employee)

    def __str__(self):
        return self.name


class ContactType(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class ContactInfo(models.Model):
    type = models.ForeignKey(ContactType)
    value = models.CharField(max_length=200)

    employee = models.ForeignKey(Employee)

    def __str__(self):
        return self.value

employee/forms.py
from django import forms

from employee.models import ContactType, Employee, ContactInfo

# detail_type_list = list((detail.id, detail.name) for detail in ContactType.objects.all())


class EmployeeForm(forms.ModelForm):
    def get_id(self):
        if self.instance:
            return self.instance.id

    class Meta:
        model = Employee
        fields = ['name', 'description']
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'description': forms.Textarea(attrs={'class': 'form-control', 'rows': 3})
        }


class EmployeeDetailForm(forms.ModelForm):
    error_css_class = 'bg-danger'
    required_css_class = 'required'

    def __init__(self, *args, **kwargs):
        super(EmployeeDetailForm, self).__init__(*args, **kwargs)
        self.fields['contact_type'].empty_label = None
        # self.auto_id = False

    def has_error_class(self):
        if any(self.errors):
            return self.error_css_class
        else:
            return ''

    class Meta:
        model = ContactInfo
        fields = ['type', 'value']
        widgets = {
            'type': forms.Select(attrs={'class': 'form-control select-noarrow'}),
            'value': forms.TextInput(attrs={'class': 'form-control'})
        }


class ContragentSearchForm(forms.Form):
    search = forms.CharField(min_length=3)

employee/views.py
import datetime

from django.http import Http404, JsonResponse
from django.shortcuts import render, get_object_or_404, get_list_or_404, redirect
from django.forms import formset_factory, modelformset_factory
from django.views import generic

from digital_key.support import DigitalKeyWrapper
from employee.forms import *
from digital_key.models import DigitalKey
from .models import Employee, ContactInfo, EmployeeGroup


# Create your views here.
class KeyListWrapper:
    def __init__(self, employee):
        keys = {}

        for key in employee.cert_set.all():
            keys[key.pk] = EmployeeKeyWrapper(key, in_cert=True)

        for key in employee.key_set.all():
            wkey = keys.get(key.pk, EmployeeKeyWrapper(key))
            wkey.in_hold = True
            keys[key.pk] = wkey

        grp_ids = employee.employeegroup_set.values('id')
        for key in DigitalKey.objects.filter(employee_group__in=grp_ids):
            wkey = keys.get(key.pk, EmployeeKeyWrapper(key))
            wkey.in_group = True
            keys[key.pk] = wkey

        self.keys = keys

    def __iter__(self):
        return iter(sorted(
            self.keys.values(),
            key=lambda e: (e.key.date_expire if e.key.date_expire else datetime.date(9999, 1, 1))
        ))


class EmployeeKeyWrapper(DigitalKeyWrapper):
    def __init__(self, digital_key: DigitalKey, in_cert=False, in_hold=False, in_group=False):
        super(EmployeeKeyWrapper, self).__init__(digital_key, default_style='success')
        self.in_cert = in_cert
        self.in_hold = in_hold
        self.in_group = in_group


class EmployeeListView(generic.ListView):
    model = Employee
    template_name = 'employee/emp_list.html'
    context_object_name = 'employees'
    allow_empty = True


# def show_all(request):
#     return render(request, 'employee/key_list.html', {
#         'employees': Employee.objects.all()
#     })


def show_by_id(request, cid: int):
    employee = get_object_or_404(Employee, pk=cid)
    cert_keys = DigitalKey.objects.filter(cert_holder=employee).order_by('date_expire')
    wrapped_list = KeyListWrapper(employee)
    return render(request, 'employee/emp_detail.html', {
        'employee': employee,
        'groups': employee.employeegroup_set.all(),
        'key_views': (DigitalKeyWrapper(key) for key in cert_keys)
    })


def show_group_by_id(request, pk):
    group = get_object_or_404(EmployeeGroup, pk=pk)
    members = group.members.all()
    wrp_keys = (DigitalKeyWrapper(key) for key in group.digitalkey_set.all())
    return render(request, 'employee/group_detail.html', {
        'group': group,
        'members': members,
        'wrp_keys': wrp_keys
    })


def show_all_by_type(request, ctype):
    employees = Employee.objects.filter(digitalkeycontact__type=ctype[:1]).distinct()
    if not employees:
        raise Http404('Контакты')
    return render(request, 'employee/emp_list.html', {
        'employees': employees
    })


def edit_by_id(request, cid: int):
    employee = get_object_or_404(Employee, pk=cid)
    info_set = employee.contactinfo_set.all()
    ContactInfoFormSet = modelformset_factory(
        ContactInfo, form=EmployeeDetailForm,
        extra=0, can_delete=True)
    if request.method == 'POST':
        contragent_form = EmployeeForm(request.POST, instance=employee)
        info_formset = ContactInfoFormSet(request.POST, queryset=info_set)
        if contragent_form.is_valid() and info_formset.is_valid():
            if contragent_form.has_changed():
                employee = contragent_form.save()
            if info_formset.has_changed():
                info_formset.save_existing_objects()
                info_formset.saved_forms = []
                for contact_info in info_formset.save_new_objects(commit=False):
                    contact_info.contact = employee
                    contact_info.save()
            return redirect('employee:show_by_id', employee.id)
    else:
        contragent_form = EmployeeForm(instance=employee)
        info_formset = ContactInfoFormSet(queryset=info_set)

    return render(request, 'employee/emp_edit.html', {
        'contragent_form': contragent_form,
        'info_formset': info_formset
    })


def create(request):
    ContactInfoFormSet = formset_factory(EmployeeDetailForm, extra=1, can_delete=True)
    if request.method == 'POST':
        contragent_form = EmployeeForm(request.POST)
        info_formset = ContactInfoFormSet(request.POST)
        if contragent_form.is_valid():
            contragent = contragent_form.save()
            if info_formset.is_valid():
                for form in info_formset.forms:
                    contact_info = form.save(commit=False)
                    contact_info.contact = contragent
                    contact_info.save()
            return redirect('employee:show_by_id', contragent.id)
    else:
        contragent_form = EmployeeForm()
        info_formset = ContactInfoFormSet()
    return render(request, 'employee/emp_edit.html', {
        'contragent_form': contragent_form,
        'info_formset': info_formset
    })


def remove_by_id(request, cid):
    employee = get_object_or_404(Employee, pk=cid)
    employee.delete()
    return redirect('employee:all')


def show_all_by_name(request):
    if request.method == 'GET':
        form = ContragentSearchForm(request.GET)
        if form.is_valid():
            name = form.cleaned_data['search']
            agents = Employee.objects.filter(name__icontains=name).values('id', 'name')
            response = JsonResponse(list(agents), safe=False)
            return response
    else:
        return JsonResponse({})


class EmployeeGroupsList(generic.ListView):
    model = EmployeeGroup
    template_name = 'employee/group_list.html'
    context_object_name = 'groups'
    allow_empty = True


def group_all(request):
    groups = EmployeeGroup.objects.all()

    return None

employee/templates/employee/detail.html
{% extends 'base.html' %}
{% block content %}
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    Контрагент:
                    <a href="{% url 'employee:edit_by_id' employee.id %}">
                        <span class="glyphicon glyphicon-pencil pull-right"></span>
                    </a>
                </div>
                <div class="panel-body">
                    <div class="rov">
                        <div class="col-md-4"><strong>{{ employee.name }}</strong></div>
                        <div class="col-md-8">{{ employee.description }}</div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-3">
            <div class="panel panel-default">
                <div class="panel-heading">
                    Контактные данные:
                </div>
                <div class="panel-body">
                    {% for detail in employee.get_contact_info %}
                        <p><strong>{{ detail.type }}:</strong> {{ detail }}</p>
                    {% endfor %}
                </div>
            </div>
        </div>
        <div class="col-md-3">
            <div class="panel panel-default">
                <div class="panel-heading">Группы:</div>
                <div class="panel-body">
                    <ul>
                        {% for group in groups %}
                            <li><a href="{% url 'employee:group_detail' group.id %}">{{ group }}</a></li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <div class="panel panel-default">
                <div class="panel-heading">Сертификаты:</div>
                <div class="panel-body">
                    <ol>
{#                        {% for view in wrp_cert_keys %}#}
{#                            <li>#}
{#                                <a href="{% url 'digital_key:show_by_id' view.key.id %}">{{ view.key }}</a>#}
{#                                <span class="label label-{{ view.get_label_class }}">{{ view.key.date_expire|date:'d.m.y' }}</span>#}
{#                                {% if view.key.location %}#}
{#                                    <span class="label label-default">{{ view.key.location }}</span>#}
{#                                {% endif %}#}
{#                                {% if view.key.copy_of %}#}
{#                                    <a class="label label-info" href="{% url 'digital_key:show_by_id' view.key.copy_of_id %}">#}
{#                                        копия</a>#}
{#                                {% endif %}#}
{#                            </li>#}
{#                        {% endfor %}#}
                        {% include 'digital_key/frag/key_views_list.html' %}
                    </ol>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

employee/templates/employee/edit.html
{% extends 'base.html' %}
{% block content %}
    <form method="post">
        {% csrf_token %}
        <input type="hidden" name="id" value="1">
        <div class="row">
            <div class="col-md-12">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        Контрагент:
                        {% if contragent_form.get_id %}
                        <a id="btn-remove" href="{% url 'employee:remove' contragent_form.get_id %}">
                            <span class="glyphicon glyphicon-trash pull-right"></span>
                        </a>
                        {% endif %}
                    </div>
                    <div class="panel-body">
                        <div class="rov">
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label class="control-label"
                                           for="{{ contragent_form.name.id_for_label }}">Имя:</label>
                                    {{ contragent_form.name }}
                                </div>
                            </div>
                            <div class="col-md-8">
                                <div class="form-group">
                                    <label class="control-label"
                                           for="{{ contragent_form.description.id_for_label }}">Описание:</label>
                                    {{ contragent_form.description }}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        Контактные данные:
                        <a id="contact-add" href="#">
                            <span class="glyphicon glyphicon-plus pull-right"></span>
                        </a>
                    </div>
                    <div class="panel-body" style="min-height:250px;">
                        {{ info_formset.management_form }}
                        <table id="contact-table" class="contact-table">
                            <tbody>
                            <tr id="tr_proto" style="display: none">
                                <td>{{ info_formset.empty_form.contact_type }}</td>
                                <td>{{ info_formset.empty_form.value }}</td>
                                <td>
                                    {% if info_formset.can_delete %}
                                        <input style="display: none" type="checkbox"
                                               id="id-{{ info_formset.empty_form.prefix }}-DELETE"
                                               name="{{ info_formset.empty_form.prefix }}-DELETE" value="True">
                                    {% endif %}
                                    <label for="id-{{ info_formset.empty_form.prefix }}-DELETE">
                                        <span class="btn glyphicon glyphicon-remove"></span>
                                    </label>
                                </td>
                            </tr>
                            {% for info_form in info_formset.forms %}
                                <tr class="{{ info_form.has_error_class }}">
                                    <td>{{ info_form.contact_type }}</td>
                                    <td>{{ info_form.value }}</td>
                                    <td>
                                        {{ info_form.id }}
                                        {% if info_formset.can_delete %}
                                            <input type="checkbox" name="{{ info_form.prefix }}-DELETE"
                                                   id="id-{{ info_form.prefix }}-DELETE" style="display: none" value="True"
                                                   {% if info_form.cleaned_data.DELETE %}checked=""{% endif %}>
                                            <label for="id-{{ info_form.prefix }}-DELETE">
                                                <span class="btn glyphicon glyphicon-remove"></span>
                                            </label>
                                        {% endif %}
                                    </td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <input type="submit" value="Save" class="btn btn-default">
                <a href="{% if contragent_form.id.value %}{% url 'employee:show_by_id' contragent_form.id.value %}
                {% else %}{% url 'employee:all' %}{% endif %}"
                   class="btn btn-default">Cancel</a>
            </div>
        </div>
    </form>
    <script>
        $(function () {
            var $tRow = $('#tr_proto').detach().removeAttr('id').removeAttr('style');
            var $table = $('#contact-table');
            var $total = $('#id_form-TOTAL_FORMS');

            var onRemove = function (event) {
                $(this).closest('tr').toggleClass('removed')
            };
            $table.find('input:checked').closest('tr').addClass('removed');
            $table.find('.glyphicon-remove').click(onRemove);

            var addDetail = function (event) {
                event.preventDefault();
                var $new = $tRow.clone();
                var num = $total.val();
                $total.val(+$total.val() + 1);
                $new.find('.glyphicon-remove').click(onRemove);
                $new.find("input[name*='__prefix__'], select[name*='__prefix__'], label[for*='__prefix__']")
                    .each(function () {
                        var id = $(this).attr('id');
                        var name = $(this).attr('name');
                        var _for = $(this).attr('for');
                        if (id) $(this).attr('id', id.replace('__prefix__', num));
                        if (name) $(this).attr('name', name.replace('__prefix__', num));
                        if (_for) $(this).attr('for', _for.replace('__prefix__', num));
                    });
                $table.find('tbody').append($new);
            };

            $('#contact-add').click(addDetail);

            $('#btn-remove').click(function (e) {
                if (!confirm('Вы уверены что хотите удалить запись?')) {
                    e.preventDefault();
                }
            });
        });
    </script>
{% endblock content %}

employee/templates/employee/emp_detail.html
{% extends 'base.html' %}
{% block content %}
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    Контрагент:
                    <a href="{% url 'employee:edit_by_id' employee.id %}">
                        <span class="glyphicon glyphicon-pencil pull-right"></span>
                    </a>
                </div>
                <div class="panel-body">
                    <div class="rov">
                        <div class="col-md-4"><strong>{{ employee.name }}</strong></div>
                        <div class="col-md-8">{{ employee.description }}</div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-3">
            <div class="panel panel-default">
                <div class="panel-heading">
                    Контактные данные:
                </div>
                <div class="panel-body">
                    {% for detail in employee.get_contact_info %}
                        <p><strong>{{ detail.type }}:</strong> {{ detail }}</p>
                    {% endfor %}
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <div class="panel panel-default">
                <div class="panel-heading">Сертификаты:</div>
                <div class="panel-body">
                    <ol>
                        {% include 'digital_key/frag/key_views_list.html' %}
                    </ol>
                </div>
            </div>
        </div>
        <div class="col-md-3">
            <div class="panel panel-default">
                <div class="panel-heading">Группы:</div>
                <div class="panel-body">
                    <ul>
                        {% for group in groups %}
                            <li><a href="{% url 'employee:group_detail' group.id %}">{{ group }}</a></li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
        </div>

    </div>
{% endblock content %}

employee/templates/employee/emp_list.html
{% extends 'base.html' %}
{% block content %}
    {% comment %}    <div id="toolbar">
        <div class="form-inline" role="form">
            <a href="{% url 'employee:add' %}" class="btn btn-default">
                <span class="glyphicon glyphicon-plus"></span>
            </a>
        </div>
    </div>{% endcomment %}
    <table data-toggle="table"
           data-height="700"
           data-toolbar="#toolbar"
           data-search="true">
        <thead>
        <tr style="display:none;">
            <th data-sortable="true">Контрагент</th>
            <th data-sortable="true">Сертификаты</th>
        </tr>
        </thead>
        <tbody>
        {% for employee in employees %}
            <tr style="display:none;">
                <td><a href="{% url 'employee:show_by_id' employee.id %}">{{ employee.name }}</a></td>
                <td>{{ employee.cert_set.count }}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock content %}

employee/templates/employee/group_detail.html
{% extends 'base.html' %}
{% block content %}
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    Группа:
                </div>
                <div class="panel-body">
                    <div class="row">
                        <div class="col-md-4"><strong>{{ group.name }}</strong></div>
                        <div class="col-md-8">{{ group.description }}</div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6">
            <div class="panel panel-default">
                <div class="panel-heading">
                    Участники:
                </div>
                <div class="panel-body">
                    <ul>
                        {% for member in members %}
                            <li><a href="{% url 'employee:show_by_id' member.id %}">{{ member }}</a></li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <div class="panel panel-default">
                <div class="panel-heading">Ключи:</div>
                <div class="panel-body">
                    <ul>
                        {% for wrp in wrp_keys %}
                            <li>
                                <a href="{% url 'digital_key:show_by_id' wrp.key.id %}">{{ wrp.key }}</a>
                                <span class="label label-{{ wrp.get_label_class }}">{{ wrp.key.date_expire|date:'d.m.y' }}</span>
                                {% if wrp.key.location %}
                                    <span class="label label-default">{{ wrp.key.location }}</span>
                                {% endif %}
                            </li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

employee/templates/employee/group_list.html
{% extends 'base.html' %}
{% block content %}

    <table data-toggle="table"
           data-height="700"
           data-search="true">
        <thead>
        <tr style="display:none;">
            <th data-sortable="true">Группа</th>
            <th data-sortable="true">Сотрудники</th>
            <th data-sortable="true">Ключи</th>
        </tr>
        </thead>
        <tbody>
        {% for group in groups %}
            <tr style="display:none;">
                <td><a href="{% url 'employee:group_detail' group.id %}">{{ group.name }}</a></td>
                <td>{{ group.members.count }}</td>
                <td>{{ group.digitalkey_set.count }}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock content %}

employee/templates/employee/list.html
{% extends 'base.html' %}
{% block content %}
{% comment %}    <div id="toolbar">
        <div class="form-inline" role="form">
            <a href="{% url 'employee:add' %}" class="btn btn-default">
                <span class="glyphicon glyphicon-plus"></span>
            </a>
        </div>
    </div>{% endcomment %}
    <table data-toggle="table"
           data-height="500"
           data-toolbar="#toolbar"
           data-search="true">
        <thead>
        <tr style="display:none;">
            <th data-sortable="true">Контрагент</th>
            <th data-sortable="true">Сертификаты</th>
        </tr>
        </thead>
        <tbody>
        {% for employee in employees %}
            <tr style="display:none;">
                <td><a href="{% url 'employee:show_by_id' employee.id %}">{{ employee.name }}</a></td>
                <td>{{ employee.cert_set.count }}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock content %}