cert_center/urls.py
from django.conf.urls import url
from . import views

app_name = 'cert_center'
urlpatterns = [
    url(r'^show/(?P<pk>\d+)$', views.show_by_id, name='show_by_id'),
    url(r'^show_req/(?P<pk>\d+)$', views.show_req_by_id, name='show_req_by_id'),
    url(r'^all$', views.show_all, name='all'),
]

contragent/urls.py
from django.conf.urls import url

from . import views

app_name = 'contragent'
urlpatterns = [
    url(r'^$', views.show_all, name='all'),
    url(r'^show/(?P<ctype>holders|contacts)$', views.show_all_by_type, name='all_by_type'),
    url(r'^show/(?P<cid>[0-9]+)$', views.show_by_id, name='show_by_id'),
    url(r'^json/search$', views.show_all_by_name, name='json_by_name'),
    url(r'^edit/(?P<cid>[0-9]+)$', views.edit_by_id, name='edit_by_id'),
    url(r'^add$', views.create, name='add'),
    url(r'^remove/(?P<cid>[0-9]+)$', views.remove_by_id, name='remove'),

]

employee/urls.py
from django.conf.urls import url

from . import views

app_name = 'employee'
urlpatterns = [
    url(r'^$', views.EmployeeListView.as_view(), name='all'),
    url(r'^show/(?P<cid>[0-9]+)$', views.show_by_id, name='show_by_id'),
    url(r'^show_group/(?P<pk>\d+)$', views.show_group_by_id, name='group_detail'),
    url(r'^json/search$', views.show_all_by_name, name='json_by_name'),
    url(r'^edit/(?P<cid>[0-9]+)$', views.edit_by_id, name='edit_by_id'),
    url(r'^add$', views.create, name='add'),
    url(r'^remove/(?P<cid>[0-9]+)$', views.remove_by_id, name='remove'),

    url(r'^group/all$', views.EmployeeGroupsList.as_view(), name='group_all')

]

export/urls.py
from django.conf.urls import url
from . import views

app_name = 'export'
urlpatterns = [
    url(r'^xlsx$', views.export_key_xlsx, name='xlsx'),
]

keyHolder/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from .views import index

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^admin/', admin.site.urls, name='admin'),
    url(r'^keys/', include('digital_key.urls')),
    url(r'^employees/', include('employee.urls')),
    url(r'^centers/', include('cert_center.urls')),
    url(r'^manuals/', include('key_manual.urls')),
    url(r'^export/', include('export.urls')),
]

key_manual/urls.py
from django.conf.urls import url
from . import views

app_name = 'key_manual'

urlpatterns = [
    url(r'^all$', views.show_all, name='all'),
    url(r'^show/(?P<pk>\d+)$', views.show_by_id, name='show_by_id'),
    url(r'^get/(?P<pk>\d+)$', views.get_by_id, name='get_by_id')
]

templates/base.html
<html>
<head>
    <meta charset="UTF-8">
    {% block meta %}{% endblock %}
    <title>{% block title %}ЭЦП - {{ user }}{% endblock %}</title>

    <link rel="stylesheet" href="/static/styles/lib/bootstrap.min.css"/>

    <link rel="stylesheet" href="/static/styles/lib/bootstrap-table.min.css"/>

    <link rel="stylesheet" href="/static/styles/lib/selectize.bootstrap3.min.css"/>

    <link rel="stylesheet" href="/static/styles/lib/bootstrap-datetimepicker.min.css"/>

    <link rel="stylesheet" href="/static/styles/custom.css"/>
    {% block link %}{% endblock %}

</head>
<body>

<script src="/static/scripts/lib/jquery3.1.0.min.js"></script>
<script src="/static/scripts/lib/bootstrap.min.js"></script>

<script src="/static/scripts/lib/bootstrap-table.min.js"></script>
<script src="/static/scripts/lib/bootstrap-table-ru-RU.min.js"></script>

<script src="/static/scripts/lib/selectize.min.js"></script>

<script src="/static/scripts/lib/moment.min.js"></script>
<script src="/static/scripts/lib/moment-locale-ru.js"></script>

<script src="/static/scripts/lib/bootstrap-datetimepicker.min.js"></script>
<div class="container">
    {% block menu %}
        <nav class="navbar navbar-default">
            <div class="container-fluid">
                <!-- Brand and toggle get grouped for better mobile display -->
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                            data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                </div>
                <!-- Collect the nav links, forms, and other content for toggling -->
                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                    <ul class="nav navbar-nav">
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"
                               aria-haspopup="true" aria-expanded="false">
                                Ключи
                                <span class="caret"></span>
                            </a>
                            <ul class="dropdown-menu">
                                <li><a href="{% url 'digital_key:all' %}">Все ключи</a></li>
                                <li><a href="{% url 'digital_key:sys_all' %}">Системы</a></li>
                                <li><a href="{% url 'digital_key:asgn_all' %}">Назначение</a></li>
                                <li><a href="{% url 'digital_key:loc_all' %}">Места хранения</a></li>
                            </ul>
                        </li>

                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"
                               aria-haspopup="true" aria-expanded="false">
                                Сотрудники
                                <span class="caret"></span>
                            </a>
                            <ul class="dropdown-menu">
                                <li><a href="{% url 'employee:all' %}">Сотрудники</a></li>
                                <li><a href="{% url 'employee:group_all' %}">Группы сотрудников</a></li>
                            </ul>
                        </li>
                        <li><a href="{% url 'cert_center:all' %}" title="Удостоверяющие центры">УЦ</a></li>
                        <li><a href="{% url 'key_manual:all' %}">Инструкции</a></li>

                        {% if user.is_staff %}
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"
                               aria-haspopup="true" aria-expanded="false">
                                Экспорт<span class="caret"></span>
                            </a>
                            <ul class="dropdown-menu">
                                <li><a href="{% url 'export:xlsx' %}">XLSX</a></li>
                                <li role="separator" class="divider"></li>
                                {#                                <li><a href="{% url 'employee:all_by_type' 'holders' %}">Держатели ключей</a></li>#}
                                {#                                <li><a href="{% url 'employee:all_by_type' 'contacts' %}">Контакты по ключам</a></li>#}
                            </ul>
                        </li>
                            <li><a href="/admin">Управление</a></li>
                            {# Для сайта светить админку плохо, но тут можно #}
                        {% endif %}
                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                        {% if user.is_authenticated %}
                            <li><a href="{% url 'logout' %}">Выход</a></li>
                        {% endif %}
                    </ul>
                </div><!-- /.navbar-collapse -->
            </div><!-- /.container-fluid -->
        </nav>
    {% endblock menu %}
    <div class="row">
        <div class="col-md-12">
            {% block content %}
            {% endblock content %}
        </div>
    </div>
</div>

</body>
</html>