cert_center/urls.py
from django.conf.urls import url
from . import views

app_name = 'cert_center'
urlpatterns = [
    url(r'^show/(?P<pk>\d+)$', views.show_by_id, name='show_by_id'),
    url(r'^show_req/(?P<pk>\d+)$', views.show_req_by_id, name='show_req_by_id'),
    url(r'^all$', views.show_all, name='all'),
]

digital_key/urls.py
from django.conf.urls import url
from . import views

app_name = 'digital_key'
urlpatterns = [
    url(r'^$', views.show_all, name='all'),
    url(r'^show/(?P<key_id>[0-9]+)$', views.show_by_id, name='show_by_id'),

    url(r'^edit/(?P<key_id>[0-9]+)$', views.edit_by_id, name='edit_by_id'),
    url(r'^remove/(?P<key_id>[0-9]+)$', views.remove_by_id, name='remove_by_id'),
    url(r'^add$', views.create, name='add'),

    url(r'^loc/detail/(?P<pk>\d+)$', views.location_detail, name='loc_detail'),
    url(r'^loc/all$', views.location_list, name='loc_all'),

    url(r'^system/all$', views.system_list, name='sys_all' ),
    url(r'^system/detail/(?P<pk>\d+)$', views.system_detail, name='sys_detail'),

    url(r'^assignment/all$', views.assignment_list, name='asgn_all'),
    url(r'^assignment/detail/(?P<pk>\d+)$', views.assignment_detail, name='asgn_detail'),
]

employee/urls.py
from django.conf.urls import url

from . import views

app_name = 'employee'
urlpatterns = [
    url(r'^$', views.EmployeeListView.as_view(), name='all'),
    url(r'^show/(?P<cid>[0-9]+)$', views.show_by_id, name='show_by_id'),
    url(r'^show_group/(?P<pk>\d+)$', views.show_group_by_id, name='group_detail'),
    url(r'^json/search$', views.show_all_by_name, name='json_by_name'),
    url(r'^edit/(?P<cid>[0-9]+)$', views.edit_by_id, name='edit_by_id'),
    url(r'^add$', views.create, name='add'),
    url(r'^remove/(?P<cid>[0-9]+)$', views.remove_by_id, name='remove'),

    url(r'^group/all$', views.EmployeeGroupsList.as_view(), name='group_all')

]

export/urls.py
from django.conf.urls import url
from . import views

app_name = 'export'
urlpatterns = [
    url(r'^xlsx$', views.export_key_xlsx, name='xlsx'),
]

keyHolder/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from .views import index

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^admin/', admin.site.urls, name='admin'),
    url(r'^keys/', include('digital_key.urls')),
    url(r'^employees/', include('employee.urls')),
    url(r'^centers/', include('cert_center.urls')),
    url(r'^manuals/', include('key_manual.urls')),
    url(r'^export/', include('export.urls')),
]

digital_key/models.py
import logging

from django.db import models
from django.utils import timezone

from employee.models import Employee, EmployeeGroup
from cert_center.models import CertificationCenter

# Create your models here.


logger = logging.getLogger(__name__)


class KeyType(models.Model):
    class Meta:
        verbose_name = 'Тип'
        verbose_name_plural = 'Типы'

    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class KeyLocation(models.Model):
    class Meta:
        verbose_name = 'Место хранения'
        verbose_name_plural = 'Места хранения'

    name = models.CharField(max_length=255)
    name_full = models.CharField(max_length=255, blank=True, default='')

    description = models.TextField(blank=True)

    def __str__(self):
        return self.name


class WorkSystem(models.Model):
    class Meta:
        verbose_name = 'Используемые системы'
        verbose_name_plural = 'Используемые системы'

    name = models.CharField(max_length=255)
    name_full = models.CharField(max_length=255, blank=True, default='')

    description = models.TextField(blank=True, null=True)
    link = models.URLField(max_length=255, blank=True, null=True)

    def __str__(self):
        return self.name


class KeyAssignment(models.Model):
    class Meta:
        verbose_name = 'Назначение'
        verbose_name_plural = 'Назначения'

    name = models.CharField(max_length=200)

    name_full = models.CharField(max_length=255, blank=True, default='')

    description = models.TextField(blank=True)

    work_systems = models.ManyToManyField(WorkSystem, blank=True)

    def __str__(self):
        return self.name


class DigitalKey(models.Model):
    class Meta:
        verbose_name = 'Ключ ЭЦП'
        verbose_name_plural = 'Ключи ЭЦП'

    name = models.CharField(max_length=255, verbose_name='Наименование')
    name_full = models.CharField(max_length=255, blank=True, default='')

    serial = models.CharField(max_length=200, verbose_name='Номер ключа')
    description = models.TextField(blank=True, null=True, default='', verbose_name='Описание')

    cert_num = models.CharField(max_length=255, blank=True, default='', verbose_name='Номер сертификата')

    pin_user = models.CharField(max_length=255, blank=True, default='')
    pin_admin = models.CharField(max_length=255, blank=True, default='')
    pin_container = models.CharField(max_length=255, blank=True, default='')

    date_begin = models.DateField(blank=True, null=True, verbose_name='Начало')
    date_expire = models.DateField(blank=True, null=True, verbose_name='Истекает')

    date_checked = models.DateField(blank=True, null=True, verbose_name='Проверен')

    renewal_time = models.PositiveIntegerField(blank=True, default=0, verbose_name="Срок перевыпуска")

    type = models.ForeignKey(KeyType, blank=True, null=True, verbose_name='Тип')
    assignment = models.ForeignKey(KeyAssignment, blank=True, null=True, verbose_name='Назначение')
    location = models.ForeignKey(KeyLocation, blank=True, null=True, verbose_name='Место хранения')

    cert_holder = models.ForeignKey(Employee, blank=True, null=True, related_name='cert_set', verbose_name='Владелец')
    key_receiver = models.ForeignKey(Employee, blank=True, null=True, related_name='key_set', verbose_name='Держатель')
    employee_group = models.ForeignKey(EmployeeGroup, blank=True, null=True, verbose_name='Группа держателей')

    cert_center = models.ForeignKey(CertificationCenter, blank=True, null=True, verbose_name='УЦ')

    work_systems = models.ManyToManyField(WorkSystem, blank=True, verbose_name='Поддерживаемые системы')

    copy_of = models.ForeignKey('DigitalKey', blank=True, null=True, verbose_name='Оригинал ключа',
                                on_delete=models.SET_NULL,
                                limit_choices_to={'copy_of': None})

    def get_copies(self):
        return DigitalKey.objects.filter(copy_of=self)

    def is_copy(self):
        return bool(self.copy_of)

    def days_left(self):
        if self.date_expire:
            delta = self.date_expire - timezone.now().date()
            return delta.days
        else:
            return 0

    def __str__(self):
        return self.name

digital_key/forms.py
from django import forms
from django.forms import Textarea
from django.forms.widgets import TextInput, Select
from digital_key.models import DigitalKey


class DigitalKeyForm(forms.ModelForm):
    # description = forms.CharField(initial="", widget=Textarea(attrs={'class': 'form-control', 'rows': 4}))
    # expire = forms.DateField(input_formats=['%Y-%m-%d'], widget=TextInput)

    def get_id(self):
        if self.instance:
            return self.instance.id

    class Meta:
        model = DigitalKey
        fields = [
            'name', 'serial', 'description', 'cert_num',
            'type', 'assignment', 'cert_holder', 'cert_center',
            'location', 'key_receiver', 'employee_group',
            'date_begin', 'date_expire', 'date_checked', 'renewal_time',
        ]

digitalkey/forms.py
from django import forms
from django.forms import Textarea
from django.forms.widgets import TextInput, Select
from digitalkey.models import DigitalKey


class DigitalKeyForm(forms.ModelForm):
    description = forms.CharField(initial="", widget=Textarea(attrs={'class': 'form-control', 'rows': 4}))
    expire = forms.DateField(input_formats=['%Y-%m-%d'], widget=TextInput)

    def get_id(self):
        if self.instance:
            return self.instance.id

    class Meta:
        model = DigitalKey
        fields = ['name', 'serial', 'description', 'date_begin', 'date_expire',
                  'type', 'assignment', 'location']

digital_key/views.py
from imaplib import Response_code

from django.contrib.admin.views.decorators import staff_member_required
from django.contrib.auth.decorators import login_required
from django.core.handlers.wsgi import WSGIHandler
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.template.context import RequestContext
from django.views.generic import ListView

from digital_key.models import KeyAssignment
from .forms import DigitalKeyForm
from .models import DigitalKey, KeyLocation, WorkSystem
from .support import DigitalKeyWrapper


def _to_string(obj, default=''):
    return str(obj) if obj else default


@login_required()
def show_all(request):
    keys = DigitalKey.objects.all()
    key_views = list(DigitalKeyWrapper(key) for key in keys)
    return render(request, 'digital_key/key_list.html', {
        'key_views': key_views
    })


# class KeyAllView(ListView):
#     model = DigitalKey
#     template_name = 'digital_key/key_list.html'




@login_required()
def show_by_id(request, key_id):
    digital_key = get_object_or_404(DigitalKey, pk=key_id)
    return render(request, 'digital_key/key_detail.html', {
        'view': DigitalKeyWrapper(digital_key)
    })


@staff_member_required()
def edit_by_id(request: WSGIHandler, key_id):
    digital_key = get_object_or_404(DigitalKey, pk=key_id)
    if request.method == 'POST':
        digital_key_form = DigitalKeyForm(request.POST, instance=digital_key)
        if digital_key_form.is_valid() and digital_key_form.has_changed():
            digital_key = digital_key_form.save()
        return redirect('digital_key:show_by_id', digital_key.id)
    else:
        digital_key_form = DigitalKeyForm(instance=digital_key)

    return render(request, 'digital_key/key_edit.html', {
        'digitalkey_form': digital_key_form,
    })


def create(request):
    digital_key = DigitalKey()
    if request.method == 'POST':
        digital_key_form = DigitalKeyForm(request.POST, instance=digital_key)
        if digital_key_form.is_valid():
            digital_key = digital_key_form.save()
            holders_ids = request.POST.getlist('holders', [])
            contacts_ids = request.POST.getlist('contacts', [])
            # for _id in holders_ids:
            #     DigitalKeyContact(digital_key=digital_key, contragent_id=_id,
            #                       type=DigitalKeyContact.HOLDER).save()
            # for _id in contacts_ids:
            #     DigitalKeyContact(digital_key=digital_key, contragent_id=_id,
            #                       type=DigitalKeyContact.CONTACT).save()
            return redirect('digital_key:show_by_id', digital_key.id)
    else:
        digital_key_form = DigitalKeyForm(instance=digital_key)
    return render(request, 'digital_key/key_edit.html', {
        'digitalkey_form': digital_key_form,
        'holders': [],
        'contacts': []
    })


def remove_by_id(request, key_id):
    digital_key = get_object_or_404(DigitalKey, pk=key_id)
    digital_key.delete()
    return redirect('digital_key:all')


def location_detail(request, pk):
    location = get_object_or_404(KeyLocation, pk=pk)
    key_views = [DigitalKeyWrapper(key) for key in location.digitalkey_set.all()]
    return render(request, 'digital_key/location_detail.html', {
        'keylocation': location,
        'key_views': key_views
    })


def location_list(request):
    locations = KeyLocation.objects.all()
    return render(request, 'digital_key/location_list.html', {
        'locations': locations
    })


def system_list(request):
    systems = WorkSystem.objects.all()
    return render(request, 'digital_key/systems_list.html', {
        'systems': systems
    })


def system_detail(request, pk):
    system = get_object_or_404(WorkSystem, pk=pk)
    key_views = [DigitalKeyWrapper(key) for key in system.digitalkey_set.all()]
    return render(request, 'digital_key/system_detail.html', {
        'system': system,
        'key_views': key_views
    })


def assignment_list(request):
    assignments = KeyAssignment.objects.all()
    return render(request, 'digital_key/assignment_list.html', {
        'assignments': assignments
    })


def assignment_detail(request, pk):
    assignment = get_object_or_404(KeyAssignment, pk=pk)
    key_views = [DigitalKeyWrapper(key) for key in assignment.digitalkey_set.all()]
    return render(request, 'digital_key/assignment_detail.html', {
        'assignment': assignment,
        'key_views': key_views
    })

digitalkey/views.py
from django.core.handlers.wsgi import WSGIHandler
from django.shortcuts import render, get_object_or_404, get_list_or_404, redirect

from .forms import DigitalKeyForm
from .support import DigitalKeyWrapper
from .models import DigitalKey


def show_all(request):
    keys = DigitalKey.objects.all()
    key_views = list(DigitalKeyWrapper(key) for key in keys)
    return render(request, 'digitalkey/list.html', {
        'key_views': key_views
    })


def show_by_id(request, key_id):
    digital_key = get_object_or_404(DigitalKey, pk=key_id)
    return render(request, 'digitalkey/detail.html', {
        'view': DigitalKeyWrapper(digital_key)
    })


def edit_by_id(request: WSGIHandler, key_id):
    digital_key = get_object_or_404(DigitalKey, pk=key_id)
    # holders = digital_key.contacts.filter(digitalkeycontact__type=DigitalKeyContact.HOLDER).values('id', 'name')
    # contacts = digital_key.contacts.filter(digitalkeycontact__type=DigitalKeyContact.CONTACT).values('id', 'name')

    if request.method == 'POST':
        digital_key_form = DigitalKeyForm(request.POST, instance=digital_key)
        if digital_key_form.is_valid():
            if digital_key_form.has_changed():
                digital_key = digital_key_form.save()
            digital_key.contacts.clear()
            holders_ids = request.POST.getlist('holders', [])
            contacts_ids = request.POST.getlist('contacts', [])
            # for _id in holders_ids:
            #     DigitalKeyContact(digital_key=digital_key, contragent_id=_id,
            #                       type=DigitalKeyContact.HOLDER).save()
            #
            # for _id in contacts_ids:
            #     DigitalKeyContact(digital_key=digital_key, contragent_id=_id,
            #                       type=DigitalKeyContact.CONTACT).save()
            return redirect('digital_key:show_by_id', digital_key.id)
    else:
        digital_key_form = DigitalKeyForm(instance=digital_key)

    return render(request, 'digitalkey/edit.html', {
        'digitalkey_form': digital_key_form,
        # 'holders': holders,
        # 'contacts': contacts
    })


def create(request):
    digital_key = DigitalKey()
    if request.method == 'POST':
        digital_key_form = DigitalKeyForm(request.POST, instance=digital_key)
        if digital_key_form.is_valid():
            digital_key = digital_key_form.save()
            holders_ids = request.POST.getlist('holders', [])
            contacts_ids = request.POST.getlist('contacts', [])
            # for _id in holders_ids:
            #     DigitalKeyContact(digital_key=digital_key, contragent_id=_id,
            #                       type=DigitalKeyContact.HOLDER).save()
            # for _id in contacts_ids:
            #     DigitalKeyContact(digital_key=digital_key, contragent_id=_id,
            #                       type=DigitalKeyContact.CONTACT).save()
            return redirect('digital_key:show_by_id', digital_key.id)
    else:
        digital_key_form = DigitalKeyForm(instance=digital_key)
    return render(request, 'digitalkey/edit.html', {
        'digitalkey_form': digital_key_form,
        'holders': [],
        'contacts': []
    })


def remove_by_id(request, key_id):
    digital_key = get_object_or_404(DigitalKey, pk=key_id)
    digital_key.delete()
    return redirect('digital_key:all')

digital_key/templates/digital_key/assignment_list.html
{% extends 'base.html' %}
{% block content %}
    <div id="toolbar">
        <div class="form-inline" role="form">
        </div>
    </div>
    <table data-toggle="table"
           data-height="700"
           data-toolbar="#toolbar"
           data-search="true">
        <thead>
        <tr style="display: none">
            <th data-sortable="true">Название</th>
            <th data-sortable="true">Ключей</th>
        </tr>
        </thead>
        <tbody>
        {% for asgn in assignments %}
            <tr style="display: none">
                <td><a href="{% url 'digital_key:asgn_detail' asgn.id %}">{{ asgn.name }}</a></td>
                <td>{{ asgn.digitalkey_set.count }}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}

digital_key/templates/digital_key/detail.html
{% extends 'base.html' %}
{% block content %}
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    Основная информация:
                    <a href="{% url 'digital_key:edit_by_id' view.key.id %}">
                        <span class="glyphicon glyphicon-pencil pull-right"></span>
                    </a>
                </div>
                <div class="panel-body">
                    <div class="row">
                        <div class="col-md-5">
                            <p><strong>Наименование:</strong> {{ view.key.name }}</p>
                            <p><strong>Номер:</strong> {{ view.key.serial }}</p>
                            <p><strong>Тип носителя:</strong> {{ view.key.type }}</p>
                            <p><strong>Сертификат:</strong>
                                {% if view.key.cert_holder %}
                                    <a href="{% url 'employee:show_by_id' view.key.cert_holder_id %}">{{ view.key.cert_holder }}</a>
                                {% endif %}
                            </p>
                            {% if view.key.cert_center %}
                                <p>
                                    <strong>Удостоверяющий центр:</strong>
                                    <a href="{% url 'cert_center:show_by_id' view.key.cert_center_id %}">
                                        {{ view.key.cert_center }}
                                    </a>
                                </p>
                            {% endif %}
                        </div>
                        <div class="col-md-7">
                            <p><strong>Назначение:</strong> {{ view.key.assignment }}</p>
                            <p><strong>Описание:</strong></p>
                            <pre>{{ view.key.description }}</pre>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6">
            <div class="panel panel-default">
                <div class="panel-heading">Дополнительная информация</div>
                <div class="panel-body">
                    {% if view.key.key_receiver %}
                        <p><strong>Выдан:</strong>
                            <a href="{% url 'employee:show_by_id' view.key.key_receiver_id %}">{{ view.key.key_receiver }}</a>
                        </p>
                    {% endif %}
                    {% if view.key.employee_group %}
                        <p><strong>Группа держателей:</strong>
                            <a href="{% url 'employee:group_detail' view.key.employee_group_id %}">
                                {{ view.key.employee_group }}</a>
                        </p>
                    {% endif %}
                    {% if view.key.location %}
                        <p><strong>Место хранения:</strong>
                            <a href="{% url 'digital_key:loc_detail' view.key.location_id %}">{{ view.key.location }}</a>
                        </p>
                    {% endif %}
                    {% if view.key.work_systems.count %}
                        <p><strong>Используется в системах:</strong></p>
                        <ul>
                            {% for system in view.key.work_systems.all %}
                                <li><a href="{% url 'digital_key:sys_detail' system.id %}">{{ system.name }}</a></li>
                            {% endfor %}
                        </ul>
                    {% endif %}
                    {% if view.key.copy_of %}
                        <p><strong>Оригинал ключа:</strong>
                            <a href="{% url 'digital_key:show_by_id' view.key.copy_of_id %}">{{ view.key.copy_of }}</a>
                            <span class="label label-default">{{ view.key.copy_of.location }}</span>
                        </p>
                    {% endif %}
                    {% if view.copies_count %}
                        <p><strong>Копии ключа:</strong></p>
                        <ul>
                            {% for copy in view.key.get_copies %}
                                <li><a href="{% url 'digital_key:show_by_id' copy.id %}">{{ copy }}</a>
                                    <span class="label label-default">{{ copy.location }}</span>
                                </li>
                            {% endfor %}
                        </ul>
                    {% endif %}
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <div class="panel panel-{{ view.get_label_class }}">
                <div class="panel-heading">Сроки действия:</div>
                <div class="panel-body">
                    {% if view.key.date_begin %}
                        <p><strong>Начало:</strong> {{ view.key.date_begin|date:'Y-m-d' }}</p>
                    {% endif %}
                    {% if view.key.date_expire %}
                        <p class="text-{{ view.get_label_class }}">
                            <strong>Окончание:</strong> {{ view.key.date_expire|date:'Y-m-d' }}
                        </p>
                        <p class="text-{{ view.get_label_class }}"><strong>Истекает через:</strong> {{ view.days_left }}
                            дней</p>
                    {% endif %}
                    {% if view.key.renewal_time %}
                        <p><strong>Сроки перевыпуска:</strong> {{ view.key.renewal_time }} дней</p>
                    {% endif %}
                </div>
            </div>
        </div>
        {% if user.is_staff %}
            <div class="col-md-6">
                <div class="panel panel-info">
                    <div class="panel-heading">Служебная информация:</div>
                    <div class="panel-body">
                        <p><strong>Pin container:</strong> {{ view.key.pin_container }}</p>
                        <p><strong>Pin admin:</strong> {{ view.key.pin_admin }}</p>
                        <p><strong>Pin user:</strong> {{ view.key.pin_user }}</p>
                    </div>
                </div>
            </div>
        {% endif %}
    </div>
{% endblock %}

digital_key/templates/digital_key/key_detail.html
{% extends 'base.html' %}
{% block content %}
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    Основная информация:
                    {% if user.is_staff %}
                        <a href="{% url 'digital_key:edit_by_id' view.key.id %}">
                            <span class="glyphicon glyphicon-pencil pull-right"></span>
                        </a>
                    {% endif %}
                </div>
                <div class="panel-body">
                    <div class="row">
                        <div class="col-md-5">
                            <p><strong>Наименование:</strong> {{ view.key.name }}</p>
                            <p><strong>Номер ключа:</strong> {{ view.key.serial }}</p>
                            <p><strong>Номер сертификата:</strong> {{ view.key.cert_num }}</p>
                            <p><strong>Тип носителя:</strong> {{ view.key.type }}</p>
                            <p><strong>Сертификат:</strong>
                                {% if view.key.cert_holder %}
                                    <a href="{% url 'employee:show_by_id' view.key.cert_holder_id %}">{{ view.key.cert_holder }}</a>
                                {% endif %}
                            </p>
                            {% if view.key.cert_center %}
                                <p>
                                    <strong>Удостоверяющий центр:</strong>
                                    <a href="{% url 'cert_center:show_by_id' view.key.cert_center_id %}">
                                        {{ view.key.cert_center }}
                                    </a>
                                </p>
                            {% endif %}

                            <p><strong>Выдан:</strong>
                                {% if view.key.key_receiver %}
                                    <a href="{% url 'employee:show_by_id' view.key.key_receiver_id %}">{{ view.key.key_receiver }}</a>
                                {% endif %}
                            </p>
                            <p><strong>Группа держателей:</strong>
                                {% if view.key.employee_group %}
                                    <a href="{% url 'employee:group_detail' view.key.employee_group_id %}">
                                        {{ view.key.employee_group }}</a>
                                {% endif %}
                            </p>
                            <p><strong>Место хранения:</strong>
                                {% if view.key.location %}
                                    <a href="{% url 'digital_key:loc_detail' view.key.location_id %}">{{ view.key.location }}</a>
                                {% endif %}
                            </p>
                            {% if view.key.work_systems.count %}
                                <p><strong>Используется в системах:</strong></p>
                                <ul>
                                    {% for system in view.key.work_systems.all %}
                                        <li><a href="{% url 'digital_key:sys_detail' system.id %}">{{ system.name }}</a>
                                        </li>
                                    {% endfor %}
                                </ul>
                            {% endif %}
                            {% if view.key.copy_of %}
                                <p><strong>Оригинал ключа:</strong>
                                    <a href="{% url 'digital_key:show_by_id' view.key.copy_of_id %}">{{ view.key.copy_of }}</a>
                                    <span class="label label-default">{{ view.key.copy_of.location }}</span>
                                </p>
                            {% endif %}
                            {% if view.copies_count %}
                                <p><strong>Копии ключа:</strong></p>
                                <ul>
                                    {% for copy in view.key.get_copies %}
                                        <li><a href="{% url 'digital_key:show_by_id' copy.id %}">{{ copy }}</a>
                                            <span class="label label-default">{{ copy.location }}</span>
                                        </li>
                                    {% endfor %}
                                </ul>
                            {% endif %}

                        </div>
                        <div class="col-md-7">
                            <p><strong>Назначение:</strong>
                                {% if view.key.assignment %}
                                    <a href="{% url 'digital_key:asgn_detail' view.key.assignment_id %}">{{ view.key.assignment }}</a>
                                {% else %}
                                    Не назначен
                                {% endif %}
                            </p>
                            <p><strong>Описание:</strong></p>
                            <pre>{{ view.key.description }}</pre>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        {% comment %}<div class="col-md-6">
            <div class="panel panel-default">
                <div class="panel-heading">Дополнительная информация</div>
                <div class="panel-body">

                </div>
            </div>
        </div>{% endcomment %}
        <div class="col-md-6">
            <div class="panel panel-{{ view.get_label_class }}">
                <div class="panel-heading">Сроки действия:</div>
                <div class="panel-body">
                    <p><strong>Начало:</strong> {{ view.key.date_begin|date:'Y-m-d' }}</p>
                    <p class="text-{{ view.get_label_class }}">
                        <strong>Окончание:</strong> {{ view.key.date_expire|date:'Y-m-d' }}
                    </p>
                    <p class="text-{{ view.get_label_class }}"><strong>Истекает через:</strong> {{ view.days_left }}
                        дней</p>
                    <p><strong>Сроки перевыпуска:</strong> {{ view.key.renewal_time }} дней</p>
                    <hr>
                    <p><strong>Проверен:</strong>
                        {{ view.key.date_checked|date:'Y-m-d' }}
                    </p>
                </div>
            </div>
        </div>
        {% if user.is_staff %}
            <div class="col-md-6">
                <div class="panel panel-info">
                    <div class="panel-heading">Служебная информация:</div>
                    <div class="panel-body">
                        <p><strong>Pin container:</strong> {{ view.key.pin_container }}</p>
                        <p><strong>Pin admin:</strong> {{ view.key.pin_admin }}</p>
                        <p><strong>Pin user:</strong> {{ view.key.pin_user }}</p>
                    </div>
                </div>
            </div>
        {% endif %}
    </div>
{% endblock %}

digital_key/templates/digital_key/location_list.html
{% extends 'base.html' %}
{% block content %}
    <div id="toolbar">
        <div class="form-inline" role="form">
        </div>
    </div>
    <table data-toggle="table"
           data-height="700"
           data-toolbar="#toolbar"
           data-search="true">
        <thead>
        <tr style="display: none">
            <th data-sortable="true">Название</th>
            <th data-sortable="true">Ключей</th>
        </tr>
        </thead>
        <tbody>
        {% for loc in locations %}
            <tr style="display: none">
                <td><a href="{% url 'digital_key:loc_detail' loc.id %}">{{ loc.name }}</a></td>
                <td>{{ loc.digitalkey_set.count }}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}